name: publish

on:
  release:
    types: [published]

jobs:
  deploy pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip pre-commit setuptools tox twine wheel

      - name: Run pre-commit
        run: |
          pre-commit run --all-files

      - name: Run tox tests
        run: |
          tox

      - name: Build and publish Python package
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python setup.py bdist_wheel
          twine check dist/*
          twine upload dist/*

  deploy docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: fkantelberg/mail-devel

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        env:
          PYTHON_VERSION: ${{ vars.PYTHON_VERSION }}
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
